[default]
src = 'src'
out = 'out'
libs = ['lib','node_modules']
ffi = true
remappings = [
    'ds-test/=lib/ds-test/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    'yearn-vaults'=lib/yearn-vaults/contracts/,
    ]

