[default]
src = 'src'
out = 'out'
libs = ['lib','node_modules']
ffi = true
remappings = [
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    # '@yearnvaults/=lib/yearn-vaults/',
    '@openzeppelin/=lib/openzeppelin-contracts/'
]

# See more config options https://github.com/gakonst/foundry/tree/master/config
